### ISSUE TITLE
Would you like a Slack notification bot for builds?

### ISSUE THREAD

**Issue by palewire** [thecityny/fullpage-react-template#10]
I have some working code I can send as a pull request, but I'd need you to do a little configuration in your Slack instance and then store a couple secrets in your organization.

**Comment by sraby** [comment]
Oh nice! Hmmm, I mean it couldn't hurt, although I don't particularly find slack to be more useful than the Github Actions window. If you wanna just share some of your code for that, we can look into it.

**Comment by kleinmatic** [comment]
Ooh! It would be great for ambient awareness if there was a slack channel that tracked deploys for the whole team. No need to see every qa build but for releases it would be very helpful.

**Comment by palewire** [comment]
I'll try to send a pull request with some GitHub secrets that you'll need to fill in.

**Comment by sraby** [comment]
hey @palewire! I just tried setting up the slack integration, but I believe Slack just changed their framework enforcing users to utilize their new ["Slack Apps" framework](https://api.slack.com/apps). I tried plugging in the `App-level Access Token` as the `BAKER_BOT_SLACK_TOKEN` but it seems that the whole Slack infrastructure doesn't align with how I've usually integrated Slack with other services. Any advice on how to solve this? Is there a different Slack token I should be plugging in?

**Comment by sraby** [comment]
See our failed workflow here: https://github.com/thecityny/fullpage-react-template/actions/runs/3577801421

**Comment by palewire** [comment]
How much longer are you working today?

**Comment by sraby** [comment]
for a few more hours! but this is not super urgent on our end so don't feel pressured to help us get a fix :)
