### ISSUE TITLE
Convert this repo into a "template"

### ISSUE THREAD

**Issue by palewire** [thecityny/fullpage-react-template#9]
If you're planning to build off this repo for future projects, I'd recommend converting it into a "template" so that it can serve as the starting point for future projects. GitHub has a guide [here](https://docs.github.com/en/repositories/creating-and-managing-repositories/creating-a-template-repository) on how to do it.

**Comment by sraby** [comment]
oh nice, thanks @palewire. Looking into this now.

**Comment by sraby** [comment]
oh wow I love this. embarrassingly have been using this repo as a template simply by copy/pasting the local repo and deleting the `.git` folder, and instantiating a new git repository there

**Comment by palewire** [comment]
Fine way to start. This is how you can level up and make it into a system.
